### ISSUE TITLE
Clicking speedchat crashes game (while in a lawbot field office)

### ISSUE THREAD

**Issue by DarthMDev** [Toontown-School-House/Toontown-School-House#18]
Traceback (most recent call last):
  File "otp\launcher\LauncherBase.py", line 1081, in mainLoop
    self._runTaskManager()
  File "otp\launcher\LauncherBase.py", line 1052, in _runTaskManager
    taskMgr.run()
  File "C:\Panda3D-1.11.0-x64\direct\task\Task.py", line 528, in run
    self.step()
  File "C:\Panda3D-1.11.0-x64\direct\task\Task.py", line 482, in step
    self.mgr.poll()
  File "C:\Panda3D-1.11.0-x64\direct\showbase\EventManager.py", line 49, in eventLoopTask
    self.doEvents()
  File "C:\Panda3D-1.11.0-x64\direct\showbase\EventManager.py", line 43, in doEvents
    processFunc(dequeueFunc())
  File "C:\Panda3D-1.11.0-x64\direct\showbase\EventManager.py", line 99, in processEvent
    messenger.send(eventName, paramList)
  File "C:\Panda3D-1.11.0-x64\direct\showbase\Messenger.py", line 333, in send
    self.__dispatch(acceptorDict, event, sentArgs, foundWatch)
  File "C:\Panda3D-1.11.0-x64\direct\showbase\Messenger.py", line 418, in __dispatch
    result = method (*(extraArgs + sentArgs))
TypeError: onMouseClick() takes exactly 2 arguments (3 given)

**Comment by DarthMDev** [comment]
Either that or it’s the countdown on the second floor
